<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Lab2\Lab2.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="11.0.0-preview.4.26230.115" />
	</ItemGroup>
</Project>

